version: '3'
services:
  recommender:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/project/static/uploads
      - ./static/images:/project/static/images
      - ./styles.csv:/project/styles.csv
      - ./embeddings.npy:/project/embeddings.npy
      - ./image_paths.npy:/project/image_paths.npy